# Generated by Django 3.2.9 on 2021-11-26 17:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('cover', models.ImageField(upload_to='')),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
