# Generated by Django 3.2.9 on 2021-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(default='', max_length=1255),
            preserve_default=False,
        ),
    ]
