# Generated by Django 3.2.9 on 2021-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_blogpost_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(upload_to='media/blogposts'),
        ),
    ]
