# Generated by Django 3.2.9 on 2021-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_alter_todoitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
