# Generated by Django 3.2.9 on 2021-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_alter_todoitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default='2021-11-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='end_time',
            field=models.TimeField(default='18:17:08'),
            preserve_default=False,
        ),
    ]
