# Generated by Django 3.2.9 on 2021-12-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0004_auto_20211205_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='date',
            new_name='End_date',
        ),
    ]
