# Generated by Django 3.2.9 on 2021-12-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_rename_date_todoitem_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='End_date',
            new_name='end_date',
        ),
    ]
