# Generated by Django 3.2.9 on 2021-11-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('review', models.IntegerField()),
                ('reviewer', models.CharField(max_length=255)),
                ('reviewer_image', models.ImageField(upload_to='project_images/<django.db.models.fields.CharField>/')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='project_images/<django.db.models.fields.related.ForeignKey>/')),
                ('caption', models.DateTimeField()),
                ('display_order', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_api.project')),
            ],
        ),
    ]
