# Generated by Django 3.2.9 on 2021-11-29 10:09

from django.db import migrations, models
import projects_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0002_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to=projects_api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='review',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='reviewer_image',
            field=models.ImageField(upload_to=projects_api.models.get_upload_path),
        ),
    ]
