# Generated by Django 3.2.9 on 2021-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0003_auto_20211129_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=255),
        ),
    ]
