# Generated by Django 3.2.9 on 2021-11-29 10:36

from django.db import migrations, models
import projects_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0004_alter_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to=projects_api.models.upload_path),
        ),
    ]
