# Generated by Django 3.2.9 on 2021-11-29 10:52

from django.db import migrations, models
import projects_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0005_alter_image_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='project_title',
            field=models.CharField(max_length=255, null='pakaipa'),
            preserve_default='pakaipa',
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to=projects_api.models.get_upload_path),
        ),
    ]
