# Generated by Django 3.2.9 on 2021-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0006_auto_20211129_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project_title',
            field=models.CharField(max_length=255),
        ),
    ]
