# Generated by Django 3.2.9 on 2021-11-29 16:55

from django.db import migrations, models
import projects_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0007_alter_image_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(default=False, upload_to=projects_api.models.get_upload_path),
            preserve_default=False,
        ),
    ]
