# Generated by Django 3.2.9 on 2021-12-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0008_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://google.com', max_length=2000),
            preserve_default=False,
        ),
    ]
